# /docker-compose.yml

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/maintenance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=dev
  frontend_user:
    build:
      context: ./frontend-user
    ports:
      - "5173:5173"
    depends_on:
      - backend
  frontend_admin:
    build:
      context: ./frontend-admin
    ports:
      - "5174:5173"
    depends_on:
      - backend
  mysql:
    image: mysql:8
    container_name: maintenance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maintenance_db
    ports:
      - "3306:3306"