spring.datasource.url=jdbc:mysql://mysql:3306/maintenance_db
spring.datasource.username=root
spring.datasource.password=password

app.default-admin.username=${DEFAULT_ADMIN_USERNAME:Admin}
app.default-admin.password=${DEFAULT_ADMIN_PASSWORD:password}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
